### ISSUE TITLE
VoltzEngine Server side crashes

### ISSUE THREAD

**Issue by dmodoomsirius** [VoltzEngine-Project/Engine#58]
https://github.com/BuiltBrokenModding/MFFS_Classic/issues/3

Found out the crash is happening on VoltzEngine's side after i disabled mffs

https://gist.github.com/dmodoomsirius/341a044c83c83141b56881a5e0cf2b0c

**Comment by DarkGuardsman** [comment]
That a bug being caused by the changes i just made to the Reference.class in VE to remove the GUIs from server side. If the error happens then something is referencing the GUI when it shouldn't.
